-function(){"use strict";var g;var h={h:function(a,b){var e=h.c();e&&e.saveStyleOverride(this,a,b);this.style[a]=b},f:function(a,b){b?this.classList.add(a):this.classList.remove(a)},u:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.textContent=a;b&&b.applyStylePreservation(this)}},s:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.innerHTML=a;b&&b.applyStylePreservation(this)}},show:function(a){this.style.display=a?"":"none"},setAttribute:function(a,b){this.setAttribute(a,
b)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=h;h.setText=h.u;h.setStyle=h.h;h.setHtml=h.s;h.addOrRemoveClassName=h.f;h.show=h.show;h.setAttribute=h.setAttribute;var m={limit:function(a,b){return b?a&&a.length&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},pluck:function(a,b){if(a){var e=b.split(".");return a.map(function(a){if(1==e.length)return a[e[0]];var b=a;e.forEach(function(a){b&&(b=b[a])});return b})}return[]},join:function(a,b){return a?a.join(b||","):""},o:function(a,b){return m.join(m.pluck(a,b))},toUpperCase:function(a){return a?a.toUpperCase():a},toLowerCase:function(a){return a?a.toLowerCase():a},w:function(a){if("undefined"!=
typeof a)return a+"px"},v:function(a){return a?a.replace(/0x/,"#"):a}};window.Formatter=m;m.limit=m.limit;m.toUpperCase=m.toUpperCase;m.toLowerCase=m.toLowerCase;m.toPixelValue=m.w;m.toHex=m.v;m.pluck=m.pluck;m.join=m.join;m.pluckAndJoin=m.o;var n=/^bind-/,p=/^style-/,q=/^class-/,r=/^each-/,t=/\/-([a-z])\/g/;function u(a){return String(a).replace(t,function(a,e){return e.toUpperCase()})}function w(a){return!(!a||!n.test(a.name))}function x(a){return!(!a||0!=a.name.indexOf("bind-each"))}function y(a){Array.prototype.slice.call(a.attributes).filter(x).forEach(function(b){a.removeAttribute(b.name)})}var z=function(){};goog.inherits(z,HTMLElement);g=z.prototype;
g.createdCallback=function(){this.a={text:"setText",html:"setHtml",show:"show"};this.b={limit:"limit",pixelvalue:"toPixelValue",uppercase:"toUpperCase",lowercase:"toLowerCase",hex:"toHex",pluck:"pluck",join:"join",pluckandjoin:"pluckAndJoin"}};g.getBinder=function(){return h};g.getFormatter=function(){return m};g.bindData=function(a,b){(b||Array.prototype.slice.call(document.querySelectorAll("*"))).forEach(this.i.bind(this,a))};
g.i=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var e,f=Array.prototype.slice.call(b.attributes),d=f.length,c=0;c<d;c++)if(x(f[c])){e=f[c];break}d=this.l.bind(this,b,a);e?d(e):f.filter(w).forEach(d)}};
g.l=function(a,b,e){var f=e.name,d=f.replace(n,""),c;c=this.getBinder();if(p.test(d)){var l=d.replace(p,"");c=c.h.bind(a,u(l))}else q.test(d)?(l=d.replace(q,""),c=c.f.bind(a,l)):r.test(d)?(c=d.replace(r,""),c=this.j.bind(this,a,c,b)):c=this.a[d]&&"function"==typeof c[this.a[d]]?c[this.a[d]]:window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[d]?window.gwd.binders[d]:c.setAttribute.bind(a,d);f=a.getAttribute(f);b=(-1!==f.indexOf("|")?this.m.bind(this,b,f):this.g.bind(this,b,f)).call(a);
"exit-override-url"==d&&a.setAttribute("exit-id",e.value.replace(/\./g,"_"));c.apply(a,[b])};
g.j=function(a,b,e,f){var d=a.parentNode;if(d){var c=a.cloneNode(!0);y(c);for(var l=[],k=0;f&&k<f.length;k++)l.push(c.cloneNode(!0));k={instances:l};c=document.createEvent("CustomEvent");c.initCustomEvent("gwdbindeachcloned",!0,!0,k);a.dispatchEvent(c);c=document.createComment("gwd-bind-each-placeholder");d.insertBefore(c,a);d.removeChild(a);A(a);if(f&&0!=f.length){for(var v,k=0;k<f.length;k++)e[b]=f[k],a=l[k],a.setAttribute("gwd-repeat-index",k),e.$index=k,v=Array.prototype.slice.call(a.querySelectorAll("*")),
this.bindData(e,v.concat(a)),d.insertBefore(a,c);delete e[b]}}};var A=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(a){a.setAttribute("gwd-bind-each-template","")})};z.prototype.g=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var e=a;b.split(".").forEach(function(a){e&&(e=e[a])});return e}return a}return null};
z.prototype.m=function(a,b){if(b){for(var e=b.split("|"),f=e.shift().trim(),f=this.g(a,f),d;0<e.length;){d=e.shift().trim();d=d.split(" ");var c=d.shift().trim();d.unshift(f);var l=this.getFormatter(),f=this.b[c]&&"function"==typeof l[this.b[c]]?l[this.b[c]].apply(this,d):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[c]?window.gwd.formatters[c].apply(this,d):f}return f}return a};z.prototype.attributeChangedCallback=null;document.registerElement("gwd-data-binder",{prototype:z.prototype});}()
